### ISSUE TITLE
Mod Conflict with Industrial Revolution (as well as possibly other fake player mods)

### ISSUE THREAD

**Issue by Pretender8** [BasiqueEvangelist/ne-v-seti#3]
Description:

    When placed and powered, the Slaughter block crashes the game/server. Issue closed by Industrial Revolution due to it being a mod conflict.

Steps to Reproduce:

    Make a new world
    Place a slaughter and a power source (used creative Lazuli Flux Container)
    World should crash in a few seconds of it being active
    Technical Information:
    Minecraft: 1.17
    Fabric API: 0.36.0
    Industrial Revolution: 1.10.0-alpha.5
    Mod using ne-v-seti: Pingspam 1.2.0

Logs:
https://gist.githubusercontent.com/natanfudge/dffc0f78b6b5905b5517a6aeb95a727b/raw/ef6854a0892ff418b79be2ed2069e1f432ea28d9/crash.txt

Notes:
>It's an incompatibility with one of the mods, specifically ``ne-v-seti: Ne v seti 0.1.5-1.17-pre1``. This will crash with any fake >players from any mod, they have to fix it on their end.

_Originally posted by @GabrielOlvH in https://github.com/GabrielOlvH/Industrial-Revolution/issues/249#issuecomment-867998768_

**Comment by BasiqueEvangelist** [comment]
Fixed in `0.1.6`.
I will release a Pingspam build with the updated version later.

**Comment by BasiqueEvangelist** [comment]
I have just released Pingspam `1.2.2`, which has Ne v seti `0.1.6` bundled with it.
